### ISSUE TITLE
UndefinedFunctionError: module "SomeModule" is not available)

### ISSUE THREAD

**Issue by minimaanima** [functional-rewire/dune#1]
Greetings,
I'm trying to load a module which is a dependency and execute several functions in it
So I in custom_allowlist.ex  I have

```
defmodule ElixirTaskRpc.CustomAllowlist do
  use Dune.Allowlist, extend: Dune.Allowlist.Default

  allow(IotToil.Protobuf, :all)
end

```
and I'm using it like
` case Dune.eval_string(code, allowlist: CustomAllowlist, max_reductions: 1_000_000) do
`
It is very strange because 7 out of 10 times it says that `** (UndefinedFunctionError) function IotToil.Protobuf.decode_protobuf/1 is undefined (module IotToil.Protobuf is not available)`

but sometimes it is running normally and the function succeeds.

Another thing is that if I call the function before invoking Dune, it runs normally and no Failure arises.

**Comment by sabiwara** [comment]
Thank you so much for the great report 💜

I was able to reproduce the issue, working on a fix.

**Comment by minimaanima** [comment]
I tried to look up and see why this was happening, but yeah... My presumption is that the module is not loaded because of the interactive mode while I'm in dev. There is a release, and that one works fine. I would be grateful if you could give me more insight because I was looking at the code, but I wasn't able to see what was wrong in Dune

**Comment by sabiwara** [comment]
Sorry for the slow response @minimaanima, I was abroad.

I didn't understand this one at first, because I was looking at the wrong place: it wasn't a module loading issue, but was actually due to the way we're encoding atoms. Basically the atom for the module itself, `IotToil.Protobuf`, would be created, but for the parser to work we also need `:IotToil` and `:Protobuf` in order to generate the AST.
So it might work after you just recompiled, but if the module is already compiled, these atoms don't need to be created in the VM anymore.

I'll release the fix, let me know if you still experience an issue.
